name: 'run diliExp'

on:
    push:
    schedule:
        -   cron: '0 */5 * * *'
    workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        repository: ${{ secrets.REPOSITORY }}
        ref: ${{ secrets.REF }}

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 执行BiliExp
      run: bash ./run_in_Actions/run_BiliExp.sh
      env:
          CONFIG: ${{ secrets.CONFIG }}

    - name: KeepAlive
      uses: gautamkrishnar/keepalive-workflow@master
